name: My First Workflow


on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v5
          
        - name: welcome msg 
          run: echo "my first job"

        - name: list files
          run: ls

        - name: read file
          run: cat READ.md